### PR TITLE
Fix integrity constraint violation issue on reindex

### LINKED ISSUE #1: Integrity constraint violation issue on running reindex
Hi,

I am facing Integrity constraint violation issue.
Here are the steps to reproduce the issue.
Magento2.2.2
PHP7.1

**Run the indexer command**
Magehackathon Bestseller indexer process unknown error:
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`kegking`.`catalog_product_entity_varchar`, CONSTRAINT `CAT_PRD_ENTT_VCHR_ENTT_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`entity_id`) REFERENCES `catalog_product_entity` (`entity_id`) ON DELETE CA), query was: INSERT INTO `catalog_product_entity_varchar` (`attribute_id`,`store_id`,`entity_id`,`value`) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)

### PR DESCRIPTION
**Pull request by zcuric**
### This PR
- [x] Fixes #1 

Credit goes to user of this comment: https://github.com/magento-hackathon/bestsellers-sorting-m2/issues/1#issuecomment-696533877

### CODE REVIEW

**Comment by peterjaap** [comment]
Thanks @rohit-prjpt and @zcuric ! :tada:

**Comment by zcuric** [comment]
@peterjaap please revert! I made some changes to composer.json that shouldn't go in! SORRY!

**Comment by peterjaap** [comment]
@zcuric the version tag is already removed by @sprankhub and the version constraint seems fine (although a little verbose). What else shouldn't go in there?

**Comment by zcuric** [comment]
@peterjaap see #7

**Comment by zcuric** [comment]
I was testing on my local test instance and left it there, so sorry! 🙈

**Pull request merged**
